### PR TITLE
Feeding with jake

### PR DESCRIPTION
**Pull request by BerkeleyPlatte**

### CODE REVIEW

**Review by MrNoIce — APPROVED** [review]
Looks good

**Comment by simplesnoh** [comment]
👍

**Comment by TheByteSizeDev** [comment]
Hey guys I think you need to resolve the conflicts with the master before we can merge it but other than that it looks awesome!

**Comment by bparker12** [comment]
I couldn't get the feed to work, but I believe I overheard that you had to do some voodoo. But dido Sydney that the conflict errors need to be resolved.

**Pull request closed without merging**
